# Generated by Django 3.2.8 on 2021-10-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
